data={'Witamina A':[['jednostka_z_recepty','gramy_roztworu','krople','jednostki'],'ilosc_na_recepcie',['producent','Hasco 45000j.m./ml','Medana 50000j.m./ml'],['gestosc','1.082','1.083','1.0','1.14','1.145','1.146','1.147','1.148','1.149','1.50']],
      'witamina E':[['jednostka_z_recepty','gramy_roztworu','krople','gramy_czystej_vit_e'],'ilosc_na_recepcie',['producent','Hasco 0,3g/ml','Medana 0,3g/ml'],['gestosc','0.928','0.929','0.930','0.931']],
      'Hydrokortyzon':['ilosc_na_recepcie','aa'],
      'Detreomycyna':['ilosc_na_recepcie','aa'],
      'Rezorcyna':['ilosc_na_recepcie','aa'],
      'Metronidazol':['ilosc_na_recepcie','aa'],
      'Mocznik':['ilosc_na_recepcie','aa','dodaj_wode'],
      'Woda destylowana':['ilosc_na_recepcie','aa','aa_ad','ad'],
      'Wazelina biała':['ilosc_na_recepcie','aa','aa_ad','ad'],
      'Wazelina żółta':['ilosc_na_recepcie','aa','aa_ad','ad'],
      'Euceryna': ['ilosc_na_recepcie', 'aa', 'aa_ad', 'ad'],
      'Lanolina':['ilosc_na_recepcie','aa','aa_ad','ad'],
      'Gliceryna 86%': ['ilosc_na_recepcie', 'aa', 'aa_ad', 'ad'],
      'Etanol':['ilosc_na_recepcie',
       ['pozadane_stezenie','10','15','20','25','30','35','40','45','50','55','60','65','70','40','96',]
      ,['uzyte_stezenie','69.6','69.7','69.8','69.8','70','70.1','70.2','70.3','70.4','70.5','70.6','95.2','95.3','95.4','95.5','95.6','95.7','95.8','95.9','96','96.1','96.2','96.3','96.4','96.5','96.6','96.7','96.8','96.9',],'aa','aa_ad','ad'],
      "Oleum Cacao":['ilosc_na_recepcie','ad','qs','czy_powiekszyc_mase_oleum'],
      'Oleum Menthae piperitae':[['jednostka_z_recepty','krople','gramy',],'ilosc_na_recepcie',['gestosc','0.901']],
      'Nystatyna':[['jednostka_z_recepty','jednostki'],'ilosc_na_recepcie',['UI_w_mg','6357']],
      '3% roztwór kwas borowy':['ilosc_na_recepcie','aa','aa_ad','ad','czy_zlozyc_roztwor_ze_skladnikow_prostych'],
      'Kwas borowy':['ilosc_na_recepcie','aa'],
      'Maść Cholesterolowa':['ilosc_na_recepcie','aa','aa_ad','ad'],
      'Balsam Peruwiański':['ilosc_na_recepcie'],
      'Ichtiol':['ilosc_na_recepcie'],'Bizmutu węglan zasadowy':['ilosc_na_recepcie'],'Bizmutu azotan zasadowy':['ilosc_na_recepcie'],
      'Prokaina':['ilosc_na_recepcie'],'Anestezyna':['ilosc_na_recepcie'],'Hascobaza':['ilosc_na_recepcie','aa','aa_ad','ad'],
      "Neomycyna":['ilosc_na_recepcie'],'Efedryna':['ilosc_na_recepcie'],'Erytromycna':['ilosc_na_recepcie'],
'Tlenek Cynku':['ilosc_na_recepcie'],'Olej Rycynowy':['ilosc_na_recepcie'],'Papaweryna':['ilosc_na_recepcie'],'Mentol':['ilosc_na_recepcie'],'Laktoza':['ilosc_na_recepcie'],
'Kwas Salicylowy':['ilosc_na_recepcie']
      }
