# Generated by Django 4.0.1 on 2022-01-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_receptura_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='aa',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='aa_ad',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='aa_ad_gramy',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='czesci',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='gramy',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='ilosc_na_recepcie',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='jednostka_z_recepty',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='jednostki',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='krople',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='mililitry',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='obey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='opakowania',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='producent',
            field=models.TextField(blank=True, choices=[('1', 'Hasco 4500j.m./ml'), ('2', 'Medana 50000j.m./ml'), ('3', 'Hasco 0,3g/ml')], null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='sumg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='sztuki',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='tabletki',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
