# Generated by Django 3.2.5 on 2022-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220116_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='ilosc_na_recepcie',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
