# Generated by Django 3.2.5 on 2022-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_skladnik_ilosc_na_recepcie'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
