# Generated by Django 3.2.5 on 2022-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_skladnik_dodaj_wode'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='pozadane_stezenie',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='uzyte_stezenie',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
