# Generated by Django 3.2.5 on 2022-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220210_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptura',
            name='ilosc_gramow',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='receptura',
            name='ilosc_masci',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='receptura',
            name='czy_ilosc_oleum_pomnozyc',
            field=models.TextField(blank=True, choices=[('1', 'czopki'), ('2', 'globulki')], null=True),
        ),
    ]
