# Generated by Django 3.2.5 on 2022-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220214_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='qs',
            field=models.CharField(default='off', max_length=20),
        ),
    ]
