# Generated by Django 3.2.5 on 2022-02-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_skladnik_qs'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='gestosc',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
