# Generated by Django 3.2.5 on 2022-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_skladnik_gestosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='woda_mocznik',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
