# Generated by Django 3.1 on 2022-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_skladnik_woda_mocznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='ad',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='receptura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
