# Generated by Django 3.2.5 on 2022-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20220226_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='aa_ad_gramy',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
