# Generated by Django 3.2.5 on 2022-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_skladnik_ilosc_na_recepcie'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='solutio',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
