# Generated by Django 3.2.5 on 2022-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_skladnik_ui_w_mg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='ilosc_wody_do_etanolu',
            field=models.CharField(blank=True, default='0', max_length=40, null=True),
        ),
    ]
