# Generated by Django 3.2.5 on 2022-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_skladnik_ilosc_wody_do_etanolu'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='czy_zlozyc_roztwor_ze_skladnikow_prostych',
            field=models.CharField(default='off', max_length=20),
        ),
    ]
