# Generated by Django 3.2.5 on 2022-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_skladnik_czy_zlozyc_roztwor_ze_skladnikow_prostych'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='woda_kwas_borowy',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
