# Generated by Django 3.2.5 on 2022-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_skladnik_woda_kwas_borowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='ilosc_kwasu_borowego_do_roztworu',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
