# Generated by Django 3.1 on 2022-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_skladnik_ilosc_kwasu_borowego_do_roztworu'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='calkowita_ilosc_gramow_wody',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='receptura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
