# Generated by Django 3.2.5 on 2022-03-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20220314_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptura',
            old_name='czopki_czy_globulk',
            new_name='czopki_czy_globulki',
        ),
    ]
