# Generated by Django 3.2.5 on 2022-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_rename_czopki_czy_globulk_receptura_czopki_czy_globulki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='date',
            field=models.DateTimeField(default='19.03.2022 11:41:52'),
        ),
    ]
