# Generated by Django 3.2.5 on 2022-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_alter_receptura_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='producent',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
