# Generated by Django 3.2.5 on 2022-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_receptura_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='obey',
            field=models.IntegerField(default='off', null=True),
        ),
    ]
