# Generated by Django 3.2.5 on 2022-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_alter_skladnik_obey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='obey',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
