# Generated by Django 3.2.5 on 2022-05-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_skladnik_czy_powiekszyc_mase_oleum'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladnik',
            name='gramy_czystej_vit_e',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='gramy_rorztworu',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
