# Generated by Django 3.1 on 2022-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_rename_gramy_rorztworu_skladnik_gramy_roztworu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receptura',
            name='nazwa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
